#!/usr/bin/env tsx
/**
 * DocuMind API Code Generator
 * ============================================================
 * Auto-runs before `npm run dev` and `npm run build` via npm lifecycle hooks.
 *
 * Strategy (in order):
 *   1. Try fetching live spec from --url (default: localhost:8000)
 *   2. Fall back to saved lib/generated/openapi.json if present
 *   3. If neither available, print warning and exit 0 (non-blocking)
 *
 * Usage:
 *   npm run generate-api                      # auto (backend at localhost:8000)
 *   npm run generate-api -- --url http://...  # specific URL
 *   npm run generate-api -- --file ./spec.json # specific file
 *   npm run generate-api -- --safe            # never fail (used by predev)
 *
 * Output:
 *   lib/generated/openapi.json   (spec snapshot)
 *   lib/generated/schema.ts      (all TypeScript types)
 *   lib/generated/client.ts      (typed apiRequest wrappers per operation)
 *   hooks/generated/use{Tag}.ts  (React Query useQuery/useMutation per tag)
 *   hooks/generated/index.ts     (barrel re-export)
 * ============================================================
 */

import fs from "fs";
import path from "path";
import http from "http";
import https from "https";

// ─── CLI flags ────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const getArg = (flag: string) => {
  const idx = args.indexOf(flag);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : null;
};
const SAFE_MODE = args.includes("--safe");
const API_URL = getArg("--url") ?? "http://localhost:8000";
const LOCAL_FILE = getArg("--file");

// ─── Paths ────────────────────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, "..");
const GENERATED_LIB = path.join(ROOT, "lib", "generated");
const GENERATED_HOOKS = path.join(ROOT, "hooks", "generated");
const SNAPSHOT_PATH = path.join(GENERATED_LIB, "openapi.json");

// ─── Utilities ────────────────────────────────────────────────────────────────

function mkdirp(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function write(filePath: string, content: string) {
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`  ✅  ${path.relative(ROOT, filePath)}`);
}

function fetchJson(url: string, timeoutMs = 5000): Promise<any> {
  return new Promise((resolve, reject) => {
    const client = url.startsWith("https") ? https : http;
    const req = client.get(url, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode} from ${url}`));
        return;
      }
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => {
        try {
          resolve(JSON.parse(data));
        } catch {
          reject(new Error("Invalid JSON in response"));
        }
      });
    });
    req.on("error", reject);
    req.setTimeout(timeoutMs, () => {
      req.destroy(new Error(`Timeout fetching ${url}`));
    });
  });
}

// ─── Schema → TypeScript ──────────────────────────────────────────────────────

function schemaToTs(schema: any, depth = 0): string {
  if (!schema) return "unknown";
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop()!;
    return name;
  }
  if (schema.anyOf || schema.oneOf) {
    return (schema.anyOf ?? schema.oneOf)
      .map((s: any) => schemaToTs(s, depth))
      .join(" | ");
  }
  switch (schema.type) {
    case "string":
      if (schema.enum)
        return schema.enum.map((e: string) => `"${e}"`).join(" | ");
      return schema.format === "date-time" ? "string" : "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `Array<${schemaToTs(schema.items, depth)}>`;
    case "object": {
      if (!schema.properties) return "Record<string, unknown>";
      const pad = "  ".repeat(depth + 1);
      const fields = Object.entries<any>(schema.properties).map(([k, v]) => {
        const opt = schema.required?.includes(k) ? "" : "?";
        const nullable = v.nullable ? " | null" : "";
        return `${pad}${k}${opt}: ${schemaToTs(v, depth + 1)}${nullable};`;
      });
      return `{\n${fields.join("\n")}\n${"  ".repeat(depth)}}`;
    }
    default:
      return "unknown";
  }
}

function generateSchemaTs(spec: any): string {
  const schemas = spec.components?.schemas ?? {};
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-api.ts — do not edit manually",
    `// Source: ${spec.info?.title} v${spec.info?.version}`,
    `// Generated: ${new Date().toISOString()}`,
    "",
  ];

  for (const [name, schema] of Object.entries<any>(schemas)) {
    if (schema.enum) {
      lines.push(
        `export type ${name} = ${schema.enum.map((e: string) => `"${e}"`).join(" | ")};`
      );
      lines.push("");
      continue;
    }
    if (schema.allOf) {
      const refs = schema.allOf
        .filter((s: any) => s.$ref)
        .map((s: any) => s.$ref.split("/").pop());
      const inline = schema.allOf.find((s: any) => s.properties);
      if (refs.length > 0 && !inline) {
        lines.push(`export type ${name} = ${refs.join(" & ")};`);
      } else {
        lines.push(`export interface ${name} extends ${refs.join(", ")} {`);
        if (inline?.properties) {
          for (const [k, v] of Object.entries<any>(inline.properties)) {
            const opt = inline.required?.includes(k) ? "" : "?";
            lines.push(`  ${k}${opt}: ${schemaToTs(v)};`);
          }
        }
        lines.push("}");
      }
      lines.push("");
      continue;
    }
    if (schema.type === "object" || schema.properties) {
      const props = schema.properties ?? {};
      const required: string[] = schema.required ?? [];
      lines.push(`export interface ${name} {`);
      for (const [k, v] of Object.entries<any>(props)) {
        const opt = required.includes(k) ? "" : "?";
        const nullable = v.nullable ? " | null" : "";
        lines.push(`  ${k}${opt}: ${schemaToTs(v)}${nullable};`);
      }
      lines.push("}");
      lines.push("");
    }
  }
  return lines.join("\n");
}

// ─── Operations ───────────────────────────────────────────────────────────────

interface Op {
  operationId: string;
  method: string;
  path: string;
  tag: string;
  summary: string;
  pathParams: string[];
  queryParams: Array<{ name: string; required: boolean; type: string }>;
  hasBody: boolean;
  bodyType: string;
  returnType: string;
}

function sanitizeId(s: string): string {
  return s.replace(/[-\s]/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
}

function deriveId(method: string, rawPath: string): string {
  const cleaned = rawPath
    .replace(/^\/api\/v\d+\//, "")
    .split("/")
    .map((p) =>
      p.startsWith("{")
        ? "By" + p.slice(1, -1).charAt(0).toUpperCase() + p.slice(2, -1)
        : p.charAt(0).toUpperCase() + p.slice(1)
    )
    .join("");
  return method.toLowerCase() + cleaned;
}

function extractOps(spec: any): Op[] {
  const ops: Op[] = [];
  for (const [rawPath, pathItem] of Object.entries<any>(spec.paths ?? {})) {
    for (const method of ["get", "post", "put", "patch", "delete"]) {
      const op = pathItem[method];
      if (!op) continue;

      const tag = sanitizeId(op.tags?.[0] ?? rawPath.split("/")[3] ?? "api");
      const operationId = sanitizeId(
        op.operationId ?? deriveId(method, rawPath)
      );

      const pathParams = (rawPath.match(/\{([^}]+)\}/g) ?? []).map((p: string) =>
        p.slice(1, -1)
      );
      const queryParams = (op.parameters ?? [])
        .filter((p: any) => p.in === "query")
        .map((p: any) => ({
          name: p.name,
          required: !!p.required,
          type: schemaToTs(p.schema),
        }));

      const bodySchema =
        op.requestBody?.content?.["application/json"]?.schema;
      const bodyRef = bodySchema?.$ref?.split("/").pop();
      const bodyType = bodyRef ? `Schema.${bodyRef}` : bodySchema ? "Record<string, unknown>" : "";

      const resp =
        op.responses?.["200"]?.content?.["application/json"]?.schema ??
        op.responses?.["201"]?.content?.["application/json"]?.schema;
      const respRef = resp?.$ref?.split("/").pop();
      const returnType = respRef ? `Schema.${respRef}` : resp ? "unknown" : "void";

      ops.push({
        operationId,
        method,
        path: rawPath,
        tag,
        summary: op.summary ?? "",
        pathParams,
        queryParams,
        hasBody: !!op.requestBody,
        bodyType,
        returnType,
      });
    }
  }
  return ops;
}

// ─── Client Generator ────────────────────────────────────────────────────────

function generateClientTs(ops: Op[], spec: any): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-api.ts — do not edit manually",
    `// Generated: ${new Date().toISOString()}`,
    "",
    'import type * as Schema from "./schema";',
    'import { apiRequest } from "../http-client";',
    "",
  ];

  const byTag: Record<string, Op[]> = {};
  for (const op of ops) {
    byTag[op.tag] = byTag[op.tag] ?? [];
    byTag[op.tag].push(op);
  }

  for (const [tag, tagOps] of Object.entries(byTag)) {
    lines.push(`// ─── ${tag} ─────────────────────────────────────────────`);
    for (const op of tagOps) {
      const args: string[] = [];
      if (op.pathParams.length)
        args.push(`pathParams: { ${op.pathParams.map((p) => `${p}: string`).join("; ")} }`);
      if (op.hasBody && op.bodyType)
        args.push(`body: ${op.bodyType}`);
      if (op.queryParams.length) {
        const qt = op.queryParams
          .map((q) => `${q.name}${q.required ? "" : "?"}: ${q.type}`)
          .join("; ");
        args.push(`query?: { ${qt} }`);
      }

      const urlExpr = op.pathParams.length
        ? `\`${op.path.replace(/{([^}]+)}/g, "${pathParams.$1}")}\``
        : `"${op.path}"`;

      lines.push(`/** ${op.summary} */`);
      lines.push(`export async function ${op.operationId}(${args.join(", ")}): Promise<${op.returnType}> {`);
      lines.push(`  return apiRequest<${op.returnType}>({`);
      lines.push(`    method: "${op.method.toUpperCase()}",`);
      lines.push(`    url: ${urlExpr},`);
      if (op.hasBody) lines.push("    body,");
      if (op.queryParams.length) lines.push("    params: query,");
      lines.push("  });");
      lines.push("}");
      lines.push("");
    }
  }
  return lines.join("\n");
}

// ─── Hook Generator ───────────────────────────────────────────────────────────

const QUERY_METHODS = new Set(["get"]);

function generateHookFile(tag: string, ops: Op[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-api.ts — do not edit manually",
    `// Generated: ${new Date().toISOString()}`,
    "",
    '"use client";',
    "",
    'import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";',
    `import * as api from "@/lib/generated/client";`,
    `import type * as Schema from "@/lib/generated/schema";`,
    "",
  ];

  // Query key map
  const lower = tag.toLowerCase();
  lines.push(`export const ${lower}Keys = {`);
  lines.push(`  all: ["${lower}"] as const,`);
  for (const op of ops.filter((o) => QUERY_METHODS.has(o.method))) {
    if (op.pathParams.length) {
      const pl = op.pathParams.map((p) => `${p}: string`).join(", ");
      const pv = op.pathParams.join(", ");
      lines.push(`  ${op.operationId}: (${pl}) => [...${lower}Keys.all, "${op.operationId}", ${pv}] as const,`);
    } else {
      lines.push(`  ${op.operationId}: (params?: object) => [...${lower}Keys.all, "${op.operationId}", params] as const,`);
    }
  }
  lines.push("} as const;", "");

  for (const op of ops) {
    const hookName =
      "use" + op.operationId.charAt(0).toUpperCase() + op.operationId.slice(1);

    if (QUERY_METHODS.has(op.method)) {
      const fnArgs: string[] = [];
      if (op.pathParams.length)
        fnArgs.push(...op.pathParams.map((p) => `${p}: string`));
      if (op.queryParams.length) {
        const qt = op.queryParams.map((q) => `${q.name}${q.required ? "" : "?"}: ${q.type}`).join("; ");
        fnArgs.push(`params?: { ${qt} }`);
      }

      const keyCall = op.pathParams.length
        ? `${lower}Keys.${op.operationId}(${op.pathParams.join(", ")})`
        : `${lower}Keys.${op.operationId}(${op.queryParams.length ? "params" : ""})`;

      const apiFnArgs: string[] = [];
      if (op.pathParams.length) apiFnArgs.push(`{ ${op.pathParams.join(", ")} }`);
      if (op.queryParams.length) apiFnArgs.push("params");

      const enabledGuard = op.pathParams.length
        ? `enabled: ${op.pathParams.map((p) => `!!${p}`).join(" && ")},`
        : "";

      lines.push(`/** ${op.summary} */`);
      lines.push(`export function ${hookName}(${fnArgs.join(", ")}) {`);
      lines.push("  return useQuery({");
      lines.push(`    queryKey: ${keyCall},`);
      lines.push(`    queryFn: () => api.${op.operationId}(${apiFnArgs.join(", ")}),`);
      if (enabledGuard) lines.push(`    ${enabledGuard}`);
      lines.push("    staleTime: 30_000,");
      lines.push("  });");
      lines.push("}");
      lines.push("");
    } else {
      lines.push(`/** ${op.summary} */`);
      lines.push(`export function ${hookName}() {`);
      lines.push("  const qc = useQueryClient();");
      lines.push("  return useMutation({");
      lines.push(`    mutationFn: api.${op.operationId},`);
      lines.push("    onSuccess: () => {");
      lines.push(`      qc.invalidateQueries({ queryKey: ${lower}Keys.all });`);
      lines.push("    },");
      lines.push("  });");
      lines.push("}");
      lines.push("");
    }
  }
  return lines.join("\n");
}

// ─── Placeholder generator (when backend is unavailable) ──────────────────────

function generatePlaceholders() {
  mkdirp(GENERATED_LIB);
  mkdirp(GENERATED_HOOKS);

  const schemaPlaceholder = [
    "// AUTO-GENERATED placeholder — run `npm run generate-api` with backend running",
    "// This file will be replaced when the backend is available.",
    "",
    "export interface Placeholder { _placeholder: true }",
  ].join("\n");

  const clientPlaceholder = [
    "// AUTO-GENERATED placeholder — run `npm run generate-api` with backend running",
    "",
    'import { apiRequest } from "../http-client";',
    "",
    "// No operations available — start backend and run: npm run generate-api",
  ].join("\n");

  const indexPlaceholder = [
    "// AUTO-GENERATED placeholder — run `npm run generate-api` with backend running",
  ].join("\n");

  // Only write placeholders if files don't already exist
  if (!fs.existsSync(path.join(GENERATED_LIB, "schema.ts")))
    write(path.join(GENERATED_LIB, "schema.ts"), schemaPlaceholder);
  if (!fs.existsSync(path.join(GENERATED_LIB, "client.ts")))
    write(path.join(GENERATED_LIB, "client.ts"), clientPlaceholder);
  if (!fs.existsSync(path.join(GENERATED_HOOKS, "index.ts")))
    write(path.join(GENERATED_HOOKS, "index.ts"), indexPlaceholder);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("\n🚀  DocuMind API Codegen");
  console.log("─".repeat(50));

  mkdirp(GENERATED_LIB);
  mkdirp(GENERATED_HOOKS);

  // 1. Load OpenAPI spec
  let spec: any = null;

  if (LOCAL_FILE) {
    console.log(`📂  Reading spec from: ${LOCAL_FILE}`);
    try {
      spec = JSON.parse(fs.readFileSync(LOCAL_FILE, "utf-8"));
    } catch (err: any) {
      console.error(`❌  Cannot read file: ${err.message}`);
    }
  } else {
    const specUrl = `${API_URL}/api/openapi.json`;
    console.log(`🌐  Fetching spec from: ${specUrl}`);
    try {
      spec = await fetchJson(specUrl);
      console.log(`✔   Connected to backend`);
    } catch (err: any) {
      console.warn(`⚠   Backend unavailable: ${err.message}`);
      // Try snapshot fallback
      if (fs.existsSync(SNAPSHOT_PATH)) {
        console.log(`📦  Using cached snapshot: ${SNAPSHOT_PATH}`);
        try {
          spec = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf-8"));
        } catch {
          spec = null;
        }
      }
    }
  }

  // 2. Graceful fallback
  if (!spec) {
    if (SAFE_MODE) {
      console.warn(
        "\n⚠   No spec available — writing placeholder files.\n" +
        "    Start the backend and run: npm run generate-api\n"
      );
      generatePlaceholders();
      process.exit(0);
    } else {
      console.error("\n❌  No spec available. Use --safe to skip gracefully.");
      process.exit(1);
    }
  }

  console.log(`✔   Loaded: ${spec.info?.title} v${spec.info?.version}`);
  console.log(`    Paths: ${Object.keys(spec.paths ?? {}).length}  |  Schemas: ${Object.keys(spec.components?.schemas ?? {}).length}`);
  console.log("");

  // 3. Extract operations
  const ops = extractOps(spec);
  const byTag: Record<string, Op[]> = {};
  for (const op of ops) {
    byTag[op.tag] = byTag[op.tag] ?? [];
    byTag[op.tag].push(op);
  }
  console.log(`📋  ${ops.length} operations across ${Object.keys(byTag).length} tags`);
  console.log("");

  // 4. Generate schema.ts
  console.log("📝  Generating schema types…");
  write(path.join(GENERATED_LIB, "schema.ts"), generateSchemaTs(spec));

  // 5. Generate client.ts
  console.log("🔌  Generating API client…");
  write(path.join(GENERATED_LIB, "client.ts"), generateClientTs(ops, spec));

  // 6. Generate hooks per tag
  console.log("🪝  Generating React Query hooks…");
  const hookTags: string[] = [];
  for (const [tag, tagOps] of Object.entries(byTag)) {
    const normalized = tag.charAt(0).toUpperCase() + tag.slice(1);
    write(
      path.join(GENERATED_HOOKS, `use${normalized}.ts`),
      generateHookFile(normalized, tagOps)
    );
    hookTags.push(normalized);
  }

  // 7. Barrel export
  const barrel = [
    "// AUTO-GENERATED by scripts/generate-api.ts — do not edit manually",
    `// Generated: ${new Date().toISOString()}`,
    "",
    ...hookTags.map((tag) => `export * from "./use${tag}";`),
  ].join("\n");
  write(path.join(GENERATED_HOOKS, "index.ts"), barrel);

  // 8. Save spec snapshot
  write(SNAPSHOT_PATH, JSON.stringify(spec, null, 2));

  console.log("");
  console.log(`✅  Codegen complete!  Tags: ${hookTags.join(", ")}`);
  console.log("");
}

main().catch((err) => {
  if (SAFE_MODE) {
    console.warn(`\n⚠   Codegen failed (safe mode): ${err.message}\n`);
    generatePlaceholders();
    process.exit(0);
  } else {
    console.error(`\n❌  Codegen failed: ${err.message}`);
    process.exit(1);
  }
});
